# Generated by Django 3.2 on 2021-10-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
