# Generated by Django 3.2 on 2021-10-15 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='BillsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.bills')),
            ],
            options={
                'db_table': 'billsproducts',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bills_products', models.ManyToManyField(through='ventas.BillsProducts', to='ventas.Bills')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='billsproducts',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.products'),
        ),
        migrations.AddField(
            model_name='bills',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.clients'),
        ),
    ]
